name: trivy-action
on:
  workflow_dispatch
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Trivy vulnerability scanner in fs mode
      uses: AndreyLevchenko/trivy-action@severity-fix
      with:
        scan-type: 'fs'
        scan-ref: '.'
        severity: 'CRITICAL,HIGH'
        ignore-unfixed: true
        format: 'sarif'
        output: 'trivy-results.sarif'
        
    - name: Display SARIF
      run: |
        SARIF=$(cat trivy-results.sarif)
        echo "$SARIF"
